config/routes.rb
WeatherPlayground::Application.routes.draw do
  resources :weathers
  root to: "weathers#index"

end

app/models/weather.rb
class Weather < ActiveRecord::Base
  attr_accessible :day, :max, :min

  def weather_chart_data
    Weather.all.each do |r|
      "day: #{r.day}, min: #{r.min}, max: #{r.max}"
    end
  end
end


# jQuery ->
#   Morris.Line
#     element: 'climate'
#     data: weather_chart_data
#     data: [
#           {day: '1374130800', min: 53.85, max: 64.69 }
#           {day: '1374217200', min: 53.89, max: 67.79 }
#           {day: '1374303600', min: 54.8, max: 70.63 }
#           {day: '1374390000', min: 53.66, max: 67.96 }
#           {day: '1374476400', min: 54.83, max: 76.06 }
#           {day: '1374562800', min: 55.79, max: 57.98 }
#           {day: '1374649200', min: 55.67, max: 57.29 }
#           {day: '1374735600', min: 56.29, max: 56.32 }
#            ]
#     xkey: 'day'
#     ykeys: ['min','max']
#     labels: ['Min Temp', 'Max Temp']

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/weathers_controller.rb
class WeathersController < ApplicationController
  # GET /weathers
  # GET /weathers.json
  def index
    @weathers = Weather.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weathers }
    end
  end

  # GET /weathers/1
  # GET /weathers/1.json
  def show
    @weather = Weather.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weather }
    end
  end

  # GET /weathers/new
  # GET /weathers/new.json
  def new
    @weather = Weather.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weather }
    end
  end

  # GET /weathers/1/edit
  def edit
    @weather = Weather.find(params[:id])
  end

  # POST /weathers
  # POST /weathers.json
  def create
    @weather = Weather.new(params[:weather])

    respond_to do |format|
      if @weather.save
        format.html { redirect_to @weather, notice: 'Weather was successfully created.' }
        format.json { render json: @weather, status: :created, location: @weather }
      else
        format.html { render action: "new" }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weathers/1
  # PUT /weathers/1.json
  def update
    @weather = Weather.find(params[:id])

    respond_to do |format|
      if @weather.update_attributes(params[:weather])
        format.html { redirect_to @weather, notice: 'Weather was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weather.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weathers/1
  # DELETE /weathers/1.json
  def destroy
    @weather = Weather.find(params[:id])
    @weather.destroy

    respond_to do |format|
      format.html { redirect_to weathers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weathers_helper.rb
module WeathersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WeatherPlayground</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "http://cdn.oesmith.co.uk/morris-0.4.3.min.css", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script>

</body>
</html>

app/views/weathers/_form.html.haml
= form_for @weather do |f|
  - if @weather.errors.any?
    #error_explanation
      %h2= "#{pluralize(@weather.errors.count, "error")} prohibited this weather from being saved:"
      %ul
        - @weather.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :day
    = f.date_select :day
  .field
    = f.label :min
    = f.text_field :min
  .field
    = f.label :max
    = f.text_field :max
  .actions
    = f.submit 'Save'

app/views/weathers/edit.html.haml
%h1 Editing weather

= render 'form'

= link_to 'Show', @weather

= link_to 'Back', weathers_path

app/views/weathers/index.html.haml
%h1 Listing Weather

= content_tag :div, "", id: "climate", data: {weatherlore: @weathers }

app/views/weathers/new.html.haml
%h1 New weather

= render 'form'

= link_to 'Back', weathers_path

app/views/weathers/show.html.haml
%p#notice= notice

%p
  %b Day:
  = @weather.day
%p
  %b Min:
  = @weather.min
%p
  %b Max:
  = @weather.max

= link_to 'Edit', edit_weather_path(@weather)
\|
= link_to 'Back', weathers_path